### ISSUE TITLE
Permission Denied!

### ISSUE THREAD

**Issue by mayankamencherla** [SatyaPenmetsa/Razorpay-Opencart-3.0.2.0-Extension#1]
@SatyaPenmetsa 

Set up the extension and typed in the credentials, and enabled the module. However, I get routed to a page that says 
```
You do not have permission to access this page, please refer to your system administrator.
```

I am not able to make payments using the module either, and I get the following error: 
```
 Fatal error: Uncaught Exception: Error: Could not load model extension/payment/razorpay! in /Users/mayankamencherla/Sites/integrations/3.0.2.0-OpenCart/upload/system/engine/loader.php on line 89
```

Can you please help with this?

**Comment by mayankamencherla** [comment]
@SatyaPenmetsa

**Comment by SatyaPenmetsa** [comment]
Hey @mayankamencherla 

Fixed access permission issue and working on 2nd issue. I'll update you soon on 2nd issue.

**Comment by SatyaPenmetsa** [comment]
@mayankamencherla 

Make payments issue fixed.
